### ISSUE TITLE
jse_tracker: Invalid Function ID

### ISSUE THREAD

**Issue by LapplandBro** [Jump-Academy/jse#45]
Hi! I'm noticing bugs in the jse_tracker plugin, so far I haven't gotten any reports that-something isn't working, but I'll discount it here just in case.

#
> [SM] Exception reported: Invalid function id (FFFFFFFF)
> L 09/03/2023 - 12:18:56: [SM] Blaming: jse_tracker.smx
> L 09/03/2023 - 12:18:56: [SM] Call stack trace:
> L 09/03/2023 - 12:18:56: [SM]   [0] Call_StartFunction
> L 09/03/2023 - 12:18:56: [SM]   [1] Line 641, scripting/jse_tracker.sp::Native_GetPlayerProgress
> L 09/03/2023 - 12:18:56: [SM]   [3] GetPlayerProgress
> L 09/03/2023 - 12:18:56: [SM]   [4] Line 609, scripting/jse_teleport.sp::SendCourseMenu
> L 09/03/2023 - 12:18:56: [SM]   [5] Line 779, scripting/jse_teleport.sp::MenuHandler_GotoMain
#
First I get a warning from Sourcemod by octree:
#
> L 09/03/2023 - 03:46:40: [SM] Warning: plugin octree.smx is using more than 100000 handles!
#
And sometimes the following errors in the same plugin
#
> L 09/03/2023 - 06:00:14: [SM] Exception reported: Invalid index -1 (count: 18)
> L 09/03/2023 - 06:00:14: [SM] Blaming: jse_tracker.smx
> L 09/03/2023 - 06:00:14: [SM] Call stack trace:
> L 09/03/2023 - 06:00:14: [SM] [0] ArrayList.Get
> L 09/03/2023 - 06:00:14: [SM] [1] Line 357, jse_tracker_course.sp::Native_Course_GetControlPoint
> L 09/03/2023 - 06:00:14: [SM] [3] Course.iControlPoint.get
> L 09/03/2023 - 06:00:14: [SM] [4] Line 205, jse_autosave_database.sp::DB_BackupAutosaves_Client
> L 09/03/2023 - 06:00:14: [SM] [5] Line 163, jse_autosave_database.sp::DB_BackupAutosaves
> L 09/03/2023 - 06:00:14: [SM] [6] Line 178, scripting/jse_autosave.sp::Timer_Backup
#

Build - Latest, SM 1.12, MM 1.11, OS: Win

**Comment by LapplandBro** [comment]
[errors_20230903.log](https://github.com/Jump-Academy/jse/files/12505261/errors_20230903.log)
All plugins were updated to the latest version after my bot problem, then cleaned up the bug list. Please note that the server restarted at 6:00 (UTC+7), and even after the restart the error spam continues.

**Comment by LapplandBro** [comment]
Performed a second update, will check it out.

**Comment by LapplandBro** [comment]
The error is repeated on the latest build as well.

**Comment by geominorai** [comment]
I cannot seem to reproduce these errors.

Make sure you updated all the plugins in the release bundle (not just selectively, as there are changes to the include files that need recompilation) as well as the Octree plugin.  The SourceMod minimum version requirement has also been bumped to `1.12.0.7038`, so make sure to update that on your server as well.

**Comment by LapplandBro** [comment]
Updated with recommendations to the latest version.

SourceMod Version: 1.12.0.7041
SourcePawn Engine: 1.12.0.7041, jit-x86 (build 1.12.0.7041)

A check showed that - the error is present. MySQL database was completely cleaned.

> L 09/04/2023 - 19:46:48: [SM] Blaming: jse_tracker.smx
> L 09/04/2023 - 19:46:48: [SM] Call stack trace:
> L 09/04/2023 - 19:46:48: [SM]   [0] Call_StartFunction
> L 09/04/2023 - 19:46:48: [SM]   [1] Line 641, scripting/jse_tracker.sp::Native_GetPlayerProgress
> L 09/04/2023 - 19:46:48: [SM]   [3] GetPlayerProgress
> L 09/04/2023 - 19:46:48: [SM]   [4] Line 172, scripting/jse_teleport.sp::CheckProgress
> L 09/04/2023 - 19:46:48: [SM]   [5] Line 822, scripting/jse_teleport.sp::MenuHandler_GotoPlayer

**Comment by geominorai** [comment]
Can you grab the latest build again and replace all the smx in the plugins folder? A recent commit should have removed `scripting` from showing in the stack trace.

**Comment by LapplandBro** [comment]
Well, error changed:
> L 09/04/2023 - 20:19:16: [SM] Exception reported: Invalid function id (FFFFFFFF)
> L 09/04/2023 - 20:19:16: [SM] Blaming: jse_tracker.smx
> L 09/04/2023 - 20:19:16: [SM] Call stack trace:
> L 09/04/2023 - 20:19:16: [SM]   [0] Call_StartFunction
> L 09/04/2023 - 20:19:16: [SM]   [1] Line 641, jse_tracker.sp::Native_GetPlayerProgress
> L 09/04/2023 - 20:19:16: [SM]   [3] GetPlayerProgress
> L 09/04/2023 - 20:19:16: [SM]   [4] Line 172, jse_teleport.sp::CheckProgress
> L 09/04/2023 - 20:19:16: [SM]   [5] Line 822, jse_teleport.sp::MenuHandler_GotoPlayer

**Comment by geominorai** [comment]
Hmm, interesting. 

Does this happen on a particular map? Which ones have you tried?

**Comment by LapplandBro** [comment]
Only jump_academy_rc9a in maplist, nothing else.

**Comment by geominorai** [comment]
Gotcha, thanks. I'll look into this some more later today.

**Comment by geominorai** [comment]
Fixed in PR #49
